# Generated by Django 5.2.1 on 2025-09-17 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint_table',
            name='USER',
        ),
        migrations.AddField(
            model_name='complaint_table',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service_table',
            name='status',
            field=models.CharField(default='pending', max_length=200),
        ),
        migrations.AlterField(
            model_name='user_table',
            name='status',
            field=models.CharField(default='user', max_length=200),
        ),
    ]
