# Generated by Django 5.2.1 on 2025-09-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_complaint_table_user_complaint_table_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_table',
            name='due_date',
            field=models.DateField(default='2024-03-19'),
            preserve_default=False,
        ),
    ]
