# Generated by Django 5.2.6 on 2025-09-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_request_table_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_table',
            name='details',
            field=models.CharField(max_length=100),
        ),
    ]
